version: '3'

services:
  db:
     build: docker/db/ 
     image: mysql:5.7
     environment:
        MYSQL_DATABASE: db
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: onigiri1
        MYSQL_PASSWORD: onigiri1
        TZ: "Asia/Tokyo"
     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     volumes:
         # 永続化するときにマウントするdir
         - ./docker/db/mysql_data:/var/lib/mysql
         #- ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
         # 初期データを投入するSQLが格納されているdir
         #- ./docker/db/mysql_init:/docker-entrypoint-initdb.d
        
     ports:
        - "4306:3306"
  prod:
      build: .
      command: bundle exec puma -C config/puma.rb -E production -D
      stdin_open: true
      tty: true
      volumes:
          - .:/myapp
          - gem_data:/myapp/pubic
          - tmp-data:/myapp/tmp
          - log-data:/myapp/log
      ports:
          - 3000:3000
      depends_on:
          - db 
      tty: true
      stdin_open: true
      environment:
          - EDITOR=vim
      command: bundle exec rails server -b 0.0.0.0
  nginx:
    build:
      context: nginx/
    volumes:
        - gem_data:/myapp/pubic
        - tmp-data:/myapp/tmp
    ports:
        - 80:80
    depends_on: 
        - prod
volumes:
  mysql_data: 
  gem_data: 
  tmp-data: 
  log-data: 